@url_dev=http://localhost:3000/v1/api/

###
POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "nameshop" : "SHOP TUAN MINH",
    "email" : "ming183802@gmail.com",
    "password" : "deptraiso1"
}