@url_dev=http://localhost:3000/v1/api/


###
GET {{url_dev}}notification
Content-Type: application/json
x-api-key : 4d117c7798bcde495042490f26002e8aa8b3d6615c7ae598c5b883a619c897cfc2c61985b9816fb2d85292c34b16af82b6936f9b4835920012dd2af052dae372
x-client-id : 669f804f4b16a95c37bec2cc
authorization : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjlmODA0ZjRiMTZhOTVjMzdiZWMyY2MiLCJlbWFpbCI6Im1pbmcxODM4MEBnbWFpbC5jb20iLCJpYXQiOjE3NDM1MjYxMjEsImV4cCI6MTc0MzY5ODkyMX0._SLXp3sY_t61JwWcevQvXN0KDpKu3aIPkltxIywESkc

{
    "userId" : 1,
    "type" : "ALL"
}